In [1]:
import numpy as np
import os 
import matplotlib.pyplot as plt
import sys
from pathlib import Path
REPO_ROOT = Path.cwd().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from functions import Vecchia

In [14]:
B = np.random.randn(40,40)
A = B.T@B
S = [[i+1, i+2] for i in range(40)]
S[39] = []
S[38] = [39]
Snull = [[] for i in range(40)]
print(S)
C, D = Vecchia(A, Snull)

[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10], [10, 11], [11, 12], [12, 13], [13, 14], [14, 15], [15, 16], [16, 17], [17, 18], [18, 19], [19, 20], [20, 21], [21, 22], [22, 23], [23, 24], [24, 25], [25, 26], [26, 27], [27, 28], [28, 29], [29, 30], [30, 31], [31, 32], [32, 33], [33, 34], [34, 35], [35, 36], [36, 37], [37, 38], [38, 39], [39], []]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]
(1, 1)
[]
[]


In [7]:
print(C)
print(D)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[40.48847385  0.          0.         ...  0.          0.
   0.        ]
 [ 0.         67.24910015  0.         ...  0.          0.
   0.        ]
 [ 0.          0.         30.60914288 ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ... 33.06853217  0.
   0.        ]
 [ 0.          0.          0.         ...  0.         55.1383361
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
  39.25030651]]


In [8]:
print(np.diag(A))

[40.48847385 67.24910015 30.60914288 34.18149258 36.38342092 32.13346127
 35.49959422 35.51801918 39.7780504  39.95604991 45.57406877 43.21421066
 50.49030911 35.44686473 36.10175913 37.41921467 40.83412712 31.57152247
 48.72802553 46.93968607 31.96222001 31.22567659 38.10557997 43.89543336
 24.92658437 40.4787323  33.4120241  32.14286529 45.21140729 31.44976225
 40.70329142 42.5972345  49.92731399 41.40538148 39.18975434 30.18878303
 39.65891581 33.06853217 55.1383361  39.25030651]


In [16]:
print(np.linalg.norm(A - np.linalg.inv(C)@D @ np.linalg.inv(C.T)))
print(np.linalg.norm(A))

241.81375601279902
351.2850864647657
